# DO NOT DELETE: Beginning of Haskell dependencies
Keys.o : Keys.hs
TextHelper.o : TextHelper.hs
Stages.o : Stages.hs
Stages.o : Keys.hi
Stages.o : TextHelper.hi
NameValidation.o : NameValidation.hs
NameValidation.o : TextHelper.hi
Main.o : Main.hs
Main.o : NameValidation.hi
Main.o : Stages.hi
Main.o : Keys.hi
Main.o : TextHelper.hi
# DO NOT DELETE: End of Haskell dependencies
